env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:@typescript-eslint/strict"
  - "plugin:react/recommended"
  - "plugin:react/jsx-runtime"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"
  sourceType: module
  ecmaVersion: latest
  ecmaFeatures:
    jsx: true
plugins:
  - "@typescript-eslint"
  - "react"
  - "react-hooks"
settings:
  react:
    version: detect
rules:
  "no-unused-vars": off
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
  "block-scoped-var": error
  "camelcase": error
  "consistent-return": error
  "default-case-last": error
  "default-param-last": error
  "dot-notation": error
  "eqeqeq": error
  "no-duplicate-imports": error
  "no-implicit-coercion": error
  "no-invalid-this": error
  "no-magic-numbers": error
  "no-multi-assign": error
  "no-multi-str": error
  "no-new": error
  "no-param-reassign": error
  "no-shadow": error
  "no-throw-literal": error
  "no-unused-expressions": warn
  "no-useless-call": warn
  "no-useless-catch": warn
  "no-useless-rename": warn
  "no-var": error
  "no-warning-comments": warn
  "one-var":
    - error
    - never
  "prefer-const": error
  "prefer-exponentiation-operator": warn
  "prefer-promise-reject-errors": error
  "require-yield": warn
  "react/display-name": off
  "react-hooks/rules-of-hooks": error
  "react-hooks/exhaustive-deps": error
